<a href="https://colab.research.google.com/github/makhmudov-khondamir/Machine-Learning-Projects/blob/main/2.2.%20Tashkent_house_price_predicting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning

### Portfolio uchun vazifa: Toshkent shahrida uylarning narxini aniqlash.

Ushbu amaliyotda sizning vazifangiz berilgan ma`lumotlar asosida Toshkent shahridagi uylarning narxini aniqlash.

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

# Ustunlar ta'rifi
- `location` - sotilayotgan uy manzili
- `district` - uy joylashgan tuman
- `rooms` - xonalar soni
- `size` - uy maydoni (kv.m)
- `level` - uy joylashgan qavat
- `max_levels` - ja'mi qavatlar soni
- `price` - uy narxi

## Vazifani CRSIP-DM Metolodgiyasi yordamida bajaring.
<img src="https://i.imgur.com/dzZnnYi.png" alt="CRISP-DM" width="800"/>

In [ ]:
df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64
 3   size        7565 non-null   object
 4   level       7565 non-null   int64
 5   max_levels  7565 non-null   int64
 6   price       7565 non-null   object
dtypes: int64(3), object(4)
memory usage: 413.8+ KB

In [ ]:
import numpy as np

In [ ]:
ind=df[df['price']=='Договорная'].index
df['price'].replace('Договорная',np.nan,inplace=True)

<ipython-input-86-24062b3b35e5>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].replace('Договорная',np.nan,inplace=True)

In [ ]:
df['price']=pd.to_numeric(df['price'])

In [ ]:
ind=df[df['size']=='Площадьземли:1сот'].index
df['size'].replace('Площадьземли:1сот',np.nan,inplace=True)

<ipython-input-88-d1b29f14a6aa>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['size'].replace('Площадьземли:1сот',np.nan,inplace=True)

In [ ]:
df['size']=pd.to_numeric(df['size'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64
 3   size        7564 non-null   float64
 4   level       7565 non-null   int64
 5   max_levels  7565 non-null   int64
 6   price       7466 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 413.8+ KB

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor

# 1. Define feature groups
cat = ['location', 'district']
num = ['rooms', 'level', 'size', 'max_levels']

# 2. Column transformer pipeline (corrected)
preprocessor = ColumnTransformer([
    ('num', Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]), num),

    ('cat', OneHotEncoder(handle_unknown='ignore'), cat)
])

# 3. Split known and unknown prices
df_notnan = df[df['price'].notna()]
df_nan = df[df['price'].isna()]

X_notnan = df_notnan.drop('price', axis=1)
Y_notnan = df_notnan['price']

X_nan = df_nan.drop('price', axis=1)

# 4. Create imputation model pipeline
imputer_model = Pipeline([
    ('preprocessing', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

# 5. Fit model and fill missing prices
imputer_model.fit(X_notnan, Y_notnan)
df.loc[df['price'].isna(), 'price'] = imputer_model.predict(X_nan)

In [ ]:
df['size']=df['size'].fillna(df['size'].mean())

In [ ]:
df.head() #how deos this model owrks for one new data, do i need to pipeline that one, or directly

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57.0,4,4,52000.0
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52.0,4,5,56000.0
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42.0,4,4,37000.0
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65.0,1,4,49500.0
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70.0,3,5,55000.0

In [ ]:
X=df.drop('price',axis=1)
Y=df['price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,random_state=42,test_size=0.2)

In [ ]:
numericpip=Pipeline([
    ('scaler', StandardScaler())
])
categoricalpip=Pipeline([
  ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

fullpipeline=ColumnTransformer([
    ('categorical', categoricalpip, cat),
    ('numerical', numericpip, num)
])

In [ ]:
X_train_prepared = fullpipeline.fit_transform(X_train)

In [ ]:
X_test_prepared = fullpipeline.transform(X_test)

In [ ]:
RF_model=RandomForestRegressor()
RF_model.fit(X_train_prepared,Y_train)
Y_predicted = RF_model.predict(X_test_prepared)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

RF_mse=mean_squared_error(Y_test, Y_predicted)
print(np.sqrt(RF_mse))

230295.00445618693